config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese french italian japanese belgian] }


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :set_restaurant, only: [:new, :create, :show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :set_restaurant, only: [:new, :create]


  def new
    # we need @restaurant in our `simple_form_for`
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <div class="form-inputs">
    <%= f.input :name, placeholder: "Write the restaurant name here" %>
    <%= f.input :address, placeholder: "Write the restaurant name here" %>
    <%= f.input :category, placeholder: "Write the category here (out of 'chinese', 'italian', japanese, 'french' and 'belgian')" %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants:</h1>

<div class="container">
<ol>
<% @restaurants.each do |r| %>
  <li class="card"><%= link_to r.name, restaurant_path(r)%></li>
<% end %>
</ol>
</div>

app/views/restaurants/new.html.erb
<h1>Add your new restaurant below:</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2>Address: <%=  @restaurant.address%></h2>
<h3>Category: <%= @restaurant.category %></h3>


<%= link_to "Review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Add your review below:</h1>




<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>